all:
	make -C host
	make -C prime
	make -C aes
	make -C mem
	make -C crypt
	make -C caller
	make -C server
	make -C test-caller
	make -C minimal
	make -C label_image
	make -C label_image_caller
	make -C label_image_server
clean:
	make -C host clean
	make -C prime clean
	make -C aes clean
	make -C mem clean
	make -C crypt clean
	make -C caller clean
	make -C server clean
	make -C test-caller clean
	make -C minimal clean
	make -C label_image clean
	make -C label_image_caller clean
	make -C label_image_server clean
